### ISSUE TITLE
User feedback: PhET E fields simulation

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/charges-and-fields#136]
> Simulation works fine ---- however, when I make a symmetric charge distribution (e.g. a circle), with the charge on the edge, I should get E = zero inside.  I get E close to zero dead center, but not over the rest of the interior.  I realize the charges are points and not continuous but I built a few circles out of 64 points and was pretty disappointed in the results.  Exterior E field was very good results. 
> 
> Steps to reproduce:  Build a circle with symmetric charge symmetry and check E in the interior (should be zero everywhere)
> 
> Severity:  limits usefulness for using as an example for Gauss's Law

**Comment by arouinfar** [comment]
>  however, when I make a symmetric charge distribution (e.g. a circle), with the charge on the edge, I should get E = zero inside

Not exactly. For a uniformly charged spherical shell, the E-field is zero anywhere within the sphere, due to symmetry. However, a uniformly charged ring does not have the same symmetry. The E-field would be zero only at the center of ring, but anywhere else within the ring would be non-zero. Building a perfectly symmetrical ring in the sim is impossible, but getting close, you can see the electric field at the center of the ring is reasonably small.

![screen shot 2017-09-05 at 4 37 19 pm](https://user-images.githubusercontent.com/8419308/30086500-8f8ca312-9258-11e7-84c1-56ace3bbe877.png)

The good news is that with the upcoming Snap to Grid feature, users will be able to build perfectly symmetric arrangements of charge and measure the E-field at the center. 
![image](https://user-images.githubusercontent.com/8419308/30086664-905ed12e-9259-11e7-9e27-dd0f9ff4d00c.png)



> Severity: limits usefulness for using as an example for Gauss's Law

Gauss's Law is used for calculating the electric flux through a surface, not the electric field itself. A uniformly charged ring lacks the symmetry typically exploited in Gauss's Law problems, so I'm not sure what the user is trying to do here. My best guess is that the user is considering a concentric sphere within the ring of charge, which is not an appropriate Gaussian surface, and deciding that since the charge enclosed is zero, the electric field must also zero.  

@oliver-phet can you forward the user's email to me so I can respond to them directly?

**Comment by oliver-phet** [comment]
Email forwarded. Closing.
