### ISSUE TITLE
problem printing with white field arrows

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/charges-and-fields#140]
This was reported in the "Developing Interactive Simulations in HTML5" Google Group, see 
https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/h7qeZ5LuIdM:

> I have used the flash version of "charges and fields" which has a yellow background and red field arrows. The HTML5 version has a black background and white field arrows.  When printing this screen on our HP LasetJet 400 printer and  Safari browser, the black background is automatically converted to white, to save ink.  Thus the field arrows disappear in the printout.  Is ther a way to easily change the background and foreground colors?

I'll reference this issue in the Google Group, and ask the person who reported it to track the issue here.

**Comment by pixelzoom** [comment]
Putting a black stroke on the white arrows would address this.  Since there are a lot of arrows, we should get feedback from @jonathanolson on whether adding a stroke will hurt performance.

**Comment by pixelzoom** [comment]
Ah... This sim also has "Projector Mode".   I'll tell the user about that, and see if that meets his/her needs.

**Comment by arouinfar** [comment]
@pixelzoom my recommendation to the user would be to use projector mode. Thanks for reaching out to the user to let them know about the feature. Please let me know if that doesn't address their needs.

**Comment by pixelzoom** [comment]
The user replied to me via email:
> Thanks.  Projector mode is what I need.

Closing.

**Comment by pixelzoom** [comment]
Reopening. In 9/14/17 status meeting, we said that it might be worth adding a stroke around the arrows since teachers may not find "Projector Mode", and may not know that it's useful for printing.  @arouinfar your call on whether to proceed.

**Comment by arouinfar** [comment]
@pixelzoom assuming there wouldn't be any performance issues, it's only worth pursuing if the printer would be smart enough to print the black strokes around the arrows. If the printer setting doesn't print anything black, then the end result would be the same. I'll reach out to the user to find out more.

**Comment by arouinfar** [comment]
Followed up with the user to ask about the printer setting, and he replied:

>Thanks for the followup.  The printer apparently figures out that large black regions are background.  Note that in this simulation, the black box containing the charges is printed in black, but the background is white.
I am not sure the black stroke around the arrows will work, since what we need to see is the magnitude, and that won's show up well.
I think your solution of "projector mode" does what we want.  However, it would be good if selecting that was a one button toggle or a check box on the front screen, so we don't have to go through several steps to turn it on.

It's unclear whether the printer would be able to distinguish between the black background and black stroke since they would both reside in the same large, black region. Assuming the black stroke would print, it's possible that the printed version could still be missing some of the desired information like E-field strength (unless the gradient applied to the stroke too). However, I think this would still be better than printing nothing at all. 

@jonathanolson can you comment on whether or not there would adding a stroke to the E-field arrows would be a performance concern? If not, could you add the black stroke so I can test a few printers around Duane?

**Comment by jonathanolson** [comment]
Implemented (affects projector color scheme also --- let me know if it shouldn't).

**Comment by jonathanolson** [comment]
Also, performance impact should be negligible.

**Comment by arouinfar** [comment]
Thanks @jonathanolson!

**Comment by arouinfar** [comment]
Here's the print preview in Chrome and Safari (couldn't find print preview in Firefox):
<img width="639" alt="screen shot 2017-09-19 at 11 09 23 am" src="https://user-images.githubusercontent.com/8419308/30605385-2013909e-9d2b-11e7-8aaf-91db8759d48e.png">

I think the stroke looks nice and is a good fallback option for users who don't find Projector Mode. The black stroke looks fine in Projector Mode too, and may actually improve contrast between the arrows and background. 

Let's keep the black stroke @jonathanolson! Reassigning to you in case something else needs to be done to finalize the change. If not, please go ahead and close. :)

**Comment by jonathanolson** [comment]
Nope, it's in master (good to go). Presumably reopen if a maintenance release is desired.
