### ISSUE TITLE
[Measuring Tape]: Sliding tape out of bounds will remove tape line

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#15]
Happens in both CAF and GAO. If you slide the tape to the edge of the right boundary and slide it back into bounds, the tape line disappears and the distance is reset to 0. Is this intentional or should it be changed?

**Comment by aaronsamuel137** [comment]
Related to code review #13

**Comment by veillette** [comment]
Yes it is a "feature'. The two points (base and tip) are subject to drag bounds. In CAO, it is possible to change the dragBounds dynamically. If one doesn't constrain the tip, it is possible to set the measuring Tape in a state such that the tip can never be resized since the measuringTape becomes larger the the bounds. Hence the reason to make the tip subject to dragBounds. However, there are many cases where it this may prove unnecessary. We could  have an options.
isTipPositionDragBounded. That would be relatively easy to do.

**Comment by veillette** [comment]
@aaronsamuel137 , it is implemenetd. The tip of the measuring tape can/cant be dragBounded via the option isTipDragBounded.  It is set to false by default.

**Comment by aaronsamuel137** [comment]
Thanks for adding this. Seems to work as expected. Closing
