### ISSUE TITLE
Add support for the colorProfile query parameter

### ISSUE THREAD

**Issue by brent-phet** [phetsims/charges-and-fields#206]
Please add support for the `colorProfile` query parameter.

Per Matt Vonk at Pivot Interactives

> Hey all,
> I hope you're doing well.
> I'm working on an activity based on the Charges and Fields sim and I'm wondering if there's a way to make the "Projector Mode" the default.
> Thanks,
> Matt

Ie. Looking for this URL to work
https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_all.html?colorProfile=projector

**Comment by brent-phet** [comment]
P.S. - We gave him a link to the old implementation, but this simulation should support the current method.

https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_all.html?projector

**Comment by arouinfar** [comment]
> Please add support for the colorProfile query parameter.

Charges and Fields was converted from the deprecated `projector` to `colorProfile` in https://github.com/phetsims/joist/issues/371 and is behaving correctly on main:
https://bayes.colorado.edu/dev/phettest/charges-and-fields/charges-and-fields_en.html?ea&brand=phet&colorProfile=projector

The current production branch is 1.0 which was originally deployed in September 2016. This sim didn't have a standardized "color profile" until #112 in November 2016. I doubt it would be feasible to track down and cherry-pick the necessary commits to get `colorProfile=projector` into production. 

Since the feature is already supported on main, I suggest we close this issue @brent-phet.
