### ISSUE TITLE
Different pointer/object offset dragging out of the toolbox vs dragging from the play area

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#31]
When dragging out of the toolbox, the object appears at the x-coordinate of the toolbox icon and above the y-coordinate of the toolbox icon, which means the relative point can be different depending on where the user clicked in the toolbox icon.

My OS X screen shots weren't including the cursor, so I made a movie instead:

![pointers](https://cloud.githubusercontent.com/assets/679486/7716674/a60c0f70-fe52-11e4-989d-4e00a656714d.gif)

The potential issues I see here are:

(1) Inconsistency in the user interface.  This is not a severe problem but should be discussed.
(2) It may indicate a separate implementation for drag handler for drags starting in the toolbox vs in the play area, which could increase maintenance costs for the sim (unless this is required by some other feature).
(3) I discovered this in https://github.com/phetsims/scenery-phet/issues/157 Having separate logic for dragging out of the toolbox vs dragging starting in the play area could create additional complexity for together.js features (though these would surely be surmountable).

Not sure how best to proceed but I just wanted to raise the issue for discussion.

**Comment by veillette** [comment]
Thanks @samreid. There is indeed two separate dragHandlers for moving the charges. As far as I know this is unavoidable if you want to grab elements from an infinite well/bucket. You do need one attached to a static object, and one additional draghandler attached to the moving object. If there is another way to do it I would really like to know.

Typically though the two draghandlers behave in such a way that they have the same feel for the end user and it looks as if there is only one draghandler. However in this case @arouinfar made a special request for the behavior of the charges since the interview revealed that the charges didn't seem to be grabbable enough.

**Comment by veillette** [comment]
This was a design feature. Closing
