### ISSUE TITLE
TODO in ChargesAndFieldsToolboxPanel

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#35]
Noticed a TODO during code review #28:

``` js
// TODO fix the slight shift of panel
```

Not totally sure what this is referring to. Has it been taken care of? Should it be done before this sim is released?

**Comment by aaronsamuel137** [comment]
There is another TODO at the bottom of this file:

``` js
// TODO: ask JO if this is really necessary
```

**Comment by aaronsamuel137** [comment]
Another TODO in ElectricPotentialGridMobileWebGLNode:

``` js
// TODO: reduce allocations
```

**Comment by veillette** [comment]
Thanks @aaronsamuel137 

with respect to the second TODO, i had a question for @jonathanolson:
While trying to create an icon for the measuringTape I found that measuringTapeIcon cannot be an empty node but must contain a token node (in this case a rectangle). I'm not sure why this is necessary, although it did fix the problem with shifting of the panel upon resizing. Is there a more elegant way to do it? 

```
    /**
     * Returns an icon of the measuring tape
     * @private
     * @returns {Node}
     */
    createMeasuringTapeIcon: function() {
      // procedure to create an icon Image of a measuringTape
      // first, create an actual measuring tape

      var unspooledMeterTape = 30; // in view coordinates
      var measuringTape = new MeasuringTape( new Property( { name: '', multiplier: 1 } ), new Property( true ),
        {
          tipPositionProperty: new Property( new Vector2( unspooledMeterTape, 0 ) ),
          scale: 0.8 // make it a bit small
        } );
      measuringTape.setTextVisibility( false ); // let's hide the text label value (the length) for the icon

      // second, create the measuringTape icon with a token rectangle so that it is not empty
      // TODO: ask JO if this is really necessary
      var measuringTapeIcon = new Node( { children: [ new Rectangle( measuringTape.width - unspooledMeterTape, measuringTape.height - 5, measuringTape.width, measuringTape.height ) ] } );

      // Create the measuringTape icon using toImage
      measuringTape.toImage( function( image ) {
        measuringTapeIcon.children = [ new Image( image, { cursor: 'pointer' } ) ];
      }, measuringTape.width - unspooledMeterTape, measuringTape.height - 5, measuringTape.width, measuringTape.height );
      return measuringTapeIcon;
    }
  } );
```

**Comment by veillette** [comment]
Assigning to @jonathanolson: There are two things to do (1) address a TODO in ElectricPotentialGridMobileWebGLNode, (2) review the pasted code above to see if it is a sensible approach.

**Comment by jonathanolson** [comment]
> TODO: ask JO if this is really necessary

Necessary for what particularly? It looks like one pattern that would be used to ensure the correct bounds before the image is loaded, but they appear to have different bounds.

The rectangle covers an X range from a left of `measuringTape.width - unspooledMeterTape` to a right of `2 * measuringTape.width - unspooledMeterTape`, and a Y range of `measuringTape.height - 5` to `2 * measuringTape.height - 5`, which seems a bit odd, but I don't know the details.

The created Image will cover an X range from a left of `0` to a right of `measuringTape.width`, and a Y range from a top of `0` to a bottom of `measuringTape.height`.

If immediate bounds aren't important, I'd recommend measuringTape.toImageNodeAsynchronous(), since it will visually be in the same coordinate system as the measuringTape.

Can you clarify the original reasoning for the Rectangle, and for specifying an (optional) x/y/width/height to toImage() instead of getting an image more fitted around the measuringTape?

**Comment by jonathanolson** [comment]
(Also fixed my TODO in the WebGL implementation).

**Comment by veillette** [comment]
Replacing the rectangle by the measuringTape itself simplify the entire approach.

**Comment by veillette** [comment]
The last TODO was removed. Assigning to @aaronsamuel137  for review.

**Comment by aaronsamuel137** [comment]
Looks good. Closing
