### ISSUE TITLE
Add documentation to PencilNode and EraserNode

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#38]
During code review #56, I noticed tons of code like this in PencilNode and EraserNode:

``` js
    var part1Shape = new Shape().
      moveTo( 26.685, 3.47 ).
      cubicCurveToRelative( 1.545, 1.913, 2.285, 3.701, 1.867, 4.215 ).
      cubicCurveToRelative( -0.361, 0.439, -0.939, 0.843, -0.939, 0.8431 ).
      lineToRelative( -2.674, 2.055 ).
      cubicCurveToRelative( -0.151, -0.282, -1.617, -2.99, -2.446, -4.032 ).
      cubicCurveToRelative( -0.868, -1.088, -3.375, -3.22, -3.375, -3.221 ).
      lineToRelative( -0.025, -0.032 ).
      lineToRelative( 2.829, -2.175 ).
      cubicCurveToRelative( 0, 0.001, 0.191, -0.234, 0.931, -0.364 ).
      cubicCurveTo( 23.5, 0.64, 25.14, 1.553, 26.685, 3.47 ).
      close();
```

I think it would be useful to document where all of these coordinates are coming from, perhaps with a link to the source?

**Comment by veillette** [comment]
Maybe @jonathanolson  can weigh in on this. 

The pencilNode is drawn in code which can be convenient to change the colors. However all the positions are fixed and given with fixed number such as above. This pencilNode is attached to the electricPotential sensor that is dragged around.
At the time this node was created, @pixelzoom had mentionned that there were issues with downscaling figures but this may no longer be relevant since we have mipmapping.

My question is:  would is be preferable to replace all this code with a png figure instead? @arouinfar has already done the artwork.  On the other hand it does work as is. 
any opinions @aaronsamuel137 , @jonathanolson

**Comment by aaronsamuel137** [comment]
Looks like @pixelzoom decided to go with the png image in EraserNode when addressing https://github.com/phetsims/scenery-phet/issues/92. Perhaps that would be the way to go here too? But I'd like to hear other developers' opinions too.

**Comment by veillette** [comment]
For myself: The png file was checked in here: 
https://github.com/phetsims/charges-and-fields/blob/22e0547a3764d2040b1dd08d797498e4b8ffa73f/images/pencil.png

**Comment by pixelzoom** [comment]
For something as complicated as the pencil, I'd stick with an image file - PNG for now, hopefully SVG in the future.

**Comment by veillette** [comment]
Let's go with the png route. @arouinfar has the asset pencil.ai file. You can check it in or email it to me.

**Comment by pixelzoom** [comment]
In either case, please check in pencil.ai.

**Comment by arouinfar** [comment]
I've emailed the pencil.ai file to @bereaphysics to check in.

**Comment by veillette** [comment]
EraserNode was deleted by @pixelzoom and is replaced by the scenery-phet eraser. 
The PencilNode is now making use of the image (instead of the scenery code). The new png image as well as the ai file were checked in. Assigning to @aaronsamuel137 for review.

**Comment by aaronsamuel137** [comment]
Looks good to me. Closing
