### ISSUE TITLE
Equipotential lines disappear when adding an additional charge

### ISSUE THREAD

**Issue by bryo5363** [phetsims/charges-and-fields#41]
I assume this is due to the equipotential lines changing, but could they be manipulated into the correct equipotentials upon adding a new charge?

**Comment by veillette** [comment]
Good suggestion @bryo5363 . It would be preferable to have the equipotential lines 'evolve' rather than just disappear. Mathematically it is not a trivial problem since you are searching for an equipotential line that may share not common point with the previous equipotential line. In fact it may not longer exist depending on the configuration of charges. I attempted a weak version of this problem which was much easier to handle mathematically. Even in this simplified case, the performance was abysmal. It can take up to 1/10 of a second to draw a single equipotential line so it rapidly becomes very taxing.  

So it would be a very nice feature to have but very difficult to implement efficiently on non-webgl platforms.
