### ISSUE TITLE
Equipotential values block each other 

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/charges-and-fields#44]
Test device: Chromebook

Operating System: 

Browser: Chrome 43.0.2357.81

Problem description: The values of the equipotential lines will block each other. The values can't be moved along the lines or clicked to be displayed in front.

Steps to reproduce: Make a few equipotential lines which are close together, display values,

Severity:

Screenshots:
(Problem can be seen in upper-left of screenshot)
![screenshot 2015-06-22 at 1 59 46 pm](https://cloud.githubusercontent.com/assets/12610678/8291559/98b04d28-18e7-11e5-942a-8dacb3814375.png)

Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.1/charges-and-fields_en.html
Version: 1.0.0-rc.1 2015-06-22 16:50:22 UTC
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS armv7l 6946.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Language: en-US
Window: 1366x657
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: false
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.1 Mon Jun 22 2015 12:50:20 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"master"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"charges-and-fields":{"sha":"8fda05bfceb548a583cc0f84ac42afc36914bd44","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"master"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"master"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"master"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"master"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"master"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"master"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"master"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"master"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"master"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"master"}}

**Comment by veillette** [comment]
The center position of the label is the position chosen by the user. None of the labels are aware of the position of the other labels. Hence there is a possibility of overlap if the client chooses equipotential points that are near one another. 

I see three options here:
(1) Punting: this issue is only present if there are numerous equipotential lines and the checkbox 'values' has been checked.
(2) Make the black background smaller and/or more transparent. This doesnt really adress the issue but it minimizes the chance that two labels overlap or make it easier to see the label underneath
(3) develop a heuristic algorithm that takes into account the position of all other labels before laying out the value block. It can't be perfect (after all you can cover the entire screen with labels with enough potential lines) but it could in principle cover most of the common scenario.

Of course the third option is somewhat non-trivial since there is a lot of logic to put in and there will be further testing to be done down the road. I estimate that it would take one afternoon of work.

**Comment by veillette** [comment]
@arouinfar , @ariel-phet: do you care to chime in?

**Comment by ariel-phet** [comment]
Hmm, I have seen this before, it can be a bit confusing. I noticed it when I tried making very tight equipotential lines around a single charge to check if the calculations were correct, and a few numbers overlapped, at first making me think the calculations were incorrect, until I realize what was going on.

I definitely think we should minimize the black background rectangle, it is a bit bigger than it needs to be now.

It might be worth playing with transparency a little since it seems simple to implement. That might help "teach" the user that the value appears where they have decided to click. Perhaps play with that a bit and see if there is a transparency that looks good.

I do not think 3 is a good idea. It adds some complexity to the sim. More importantly I think there is "value" in the value appearing where you click to plot the equipotential line. If you have values turned on, the value appears right at the cross hairs, giving the user immediate and useful feedback as to the association of the value and the equipotential line.

**Comment by arouinfar** [comment]
I agree with @ariel-phet. Try minimizing the black rectangle and adding a little transparency, @bereaphysics.

**Comment by veillette** [comment]
The black rectangle is tighter around the text. Only 20% larger than the text (rather than 40%). The  transparency was set to 50%.

![image](https://cloud.githubusercontent.com/assets/7633344/8396836/29d34ed0-1d85-11e5-91be-2457c9710b67.png)

or

![image](https://cloud.githubusercontent.com/assets/7633344/8396846/a7b3620e-1d85-11e5-936c-ee93710e3804.png)

One unintended effect of setting the transparency to 50% is that the underlying equipotential line shows through, which hinders the readability but it shows the continuity of the line. Now  I am on the fence about setting the transparency to a non zero value. @arouinfar, @ariel-phet and @elisemorgan, any opinions

**Comment by veillette** [comment]
The release candidate 2 http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.2/charges-and-fields_en.html might partially addressed this issue

**Comment by elisemorgan** [comment]
@bereaphysics  Just out of curiosity, would it be possible to make the values draggable along their respective equipotential? I'm thinking of a user who clicks to create equipotentials before selecting values so they don't realize the values will appear where they clicked. It would be easy for them if they could drag the values to where they are all legible instead of recreating the equipotentials. 

If that's too complicated coding wise then I think the transparency helps a lot and this can be closed.

**Comment by bryo5363** [comment]
I think it would be nice to have a "bring to front" implemented so the user can get the respective value of the equipotential they would like to examine. I think the new design looks much better, especially with this issue but I think a bring to front option could be very beneficial to cleaning this up.

**Comment by veillette** [comment]
At first sight, bring to front should be relatively easy to implement. 
Draggable seems harder to do but that would be a nice feature.
Let me chew on this for a bit and i'll get back to you.

**Comment by veillette** [comment]
Thanks @elisemorgan  and @bryo5363 , these were two good ideas. Let's make sure that @arouinfar and @ariel-phet approve.. I'll put out a new dev or rc out soon.

**Comment by ariel-phet** [comment]
One worry of mine with dragging the value label would be when several charges are around and there is an overlap between the value and a placed charge. I think that could get confusing and possibly buggy.

I really like the solution as is. The main point is to alleviate confusion.

Although I think @elisemorgan and @bryo5363 have made valuable suggestions, when I really reflect on the learning goals of this sim, it is not meant to be more qualitative, so I am not sure we need to spend too much focus on complex plots with lots of tightly spaced values...that starts to get in the realm where an advanced physics student should really be using mathematica or such. 

@arouinfar - do you have thoughts?

**Comment by arouinfar** [comment]
I think that the transparency @bereaphysics implemented looks good and will achieve the goal of making the values more visible. Once students plot a few equipotential lines with the values turned on, they'll likely realize that the value appears in the center of the crosshairs. 

@elisemorgan and @bryo5363 made some excellent suggestions, but I agree with @ariel-phet that these features are tangential to the learning goals and could be complicated given the tight touch areas. 

Closing this issue, as the implementation in rc.3 looks good.
