### ISSUE TITLE
Slower performance on iPad

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/charges-and-fields#47]
Slower performance compared to desktop on iPad 2 iOS 8.3

**Comment by veillette** [comment]
@orejolaphet: can you give us some detail on what aspect(s) of the simulation is(are) slow. In addition can you tell us if webGL is enabled on this platform. (It should be indicated under 'report a problem').

**Comment by orejolaphet** [comment]
@bereaphysics performance slows down once you have 2 charges placed with the E-field displayed.
The vectors rotate very slowly and choppy on the iPad. Slow performance with WebGl enabled and ?webgl=false.

Here is the Trouble Shooting information

Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.1/charges-and-fields_en.html
Version: 1.0.0-rc.1 2015-06-22 16:50:22 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-115.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.1 Mon Jun 22 2015 12:50:20 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"master"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"charges-and-fields":{"sha":"8fda05bfceb548a583cc0f84ac42afc36914bd44","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"master"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"master"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"master"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"master"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"master"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"master"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"master"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"master"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"master"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"master"}}

**Comment by veillette** [comment]
Speed could be improved by using #7 solution.

**Comment by veillette** [comment]
I'm going to assign this issue to @ariel-phet so that he can make an executive decision. 
@arouinfar, you are welcome to chime in.

First some information: The electric field grid (the grid of arrows) behaves choppily when dragging electric charge on the board. I have not performed a recent test but it used to be between 10-15 fps. There has been a lot of optimizations on the electricField grid node. There is essentially no garbage collection going on, it constantly reuses the arrows, etc.. It relies on the svg renderer and you cant further optimize it, since there is no more fat to cut. 

If you would like to increase the performance then one should use a canvasNode. @jonathanolson might be able to ascertain more precisely the performance upside that we might gain, but my guestimate  is that we may get 30fps on the ipad. All the platforms would be improved since this is the slowest element of the sim.

However since it would rely on canvasNode, then we would not be able to use any of the scenery code (such as the arrows). Everything in a canvasNode is custom more so that implies that it is more or less unmaintainable from the point of view of software development. For instance currently it takes one line of code to add a stroke on the arrow, Using canvasNode it would essentially amount to a complete rewrite of the electricFieldGridNode. 

Personally I find that although the responsiveness of arrow field is subpar, it is not a very common or essential mode of interaction for this sim. In this sim, you mostly move the sensors around while the charges are fixed. Having the field arrows respond smoothly to the motion of charges is nice but not essential.

In any case, I leave the decision up to you. 

I estimate that it would take a day to tackle this issue.

**Comment by orejolaphet** [comment]
Slow performance on Windows 7 IE 10 as well. Similar choppy behavior to iPad

**Comment by orejolaphet** [comment]
Extremely slow performance on iPad 2 iOS 7 + Safari

**Comment by orejolaphet** [comment]
Extremely slow performance on OSX 10.10.2 FireFox 38

**Comment by veillette** [comment]
Given that it is extremely slow, and problematic on may other platforms, one ought to tackle the issue.

**Comment by veillette** [comment]
@orejolaphet: I don't have access to any of the problematic platforms. You previously mentioned that the electric field arrow grid move is not very responsive when you move an electric charge. Is there anything else that is problematic?

**Comment by veillette** [comment]
we will push to release candidate 3. In the end it turned out to be easier  than I thought, and it wont be to hard to maintain, (unlike what i said previously). There is a fair amount of trig functions/ geometry  though but i added (hopefully) enough documentation to make sense of it.

**Comment by orejolaphet** [comment]
@bereaphysics performance of the E-field has improved for rc.3 on iPad 2 iOS 7, but with voltage selected vectors still respond very slowly.

**Comment by orejolaphet** [comment]
Performance is great on  OSX 10.10.2 FireFox 38 for rc.3

**Comment by veillette** [comment]
Great to know. Turning on both the electric field and the electric potential field on the iPad was always going to be a challenge. The electric potential field is rendered with webGL and there is no more juice  we can squeeze at this point. The electric field  is now rendered through Canvas and that is certainly an improvement over svg but it doesn't have the smooth performance of webGL. It would be, in principle, possible to further optimize the e-field , by having it rendered in webGL. I'll assign to @ariel-phet  to make the call.

**Comment by elisemorgan** [comment]
@bereaphysics performance on iPad 2 iOS 8.3 is good with release candidate 3

**Comment by ariel-phet** [comment]
@arouinfar - can you take a look at this ticket and iPad 2 iOS 8.3 performance and give your opinions in this issue?

**Comment by arouinfar** [comment]
Performance on iPad2/iOS 8.3 looks good in rc.3. Reassigning to @ariel-phet.

**Comment by arouinfar** [comment]
I had about a dozen charges in the play space with E-field and Voltage on. The charges slightly trail my finger when quickly moving them around, but it doesn't seem laggy at all. The E-field arrows are very responsive, so I'm not sure we that need to render them in WebGL. Equipotential lines are also quick to draw, even with complicated charge arrangements.

**Comment by veillette** [comment]
Switching to canvas node has negative impact on win8 with chrome (see #59)

**Comment by ariel-phet** [comment]
Considering @arouinfar comments, I think we can close this issue.
