### ISSUE TITLE
Measuring tape length decreases when at a boundary

### ISSUE THREAD

**Issue by bryo5363** [phetsims/charges-and-fields#54]
The end of the measuring tape will not exceed the boundary. When moving the whole device to a boundary, the length of the tape truncates. I cannot recall if any other simulations do this but the behavior is a little strange.

**Comment by veillette** [comment]
for your information, this behavior is described as 'dragbounds'. The tip of the measuring tape is said to be subject to dragbounds, namely the bounds of the screen. 

Given that it is possible to rescale the play area by changing the size of window, one can extend the measuring tape across the diagonal. If one doesn't truncate the measuring tape upon rescaling the window, then under some scenarios the end of the measuring tape can become unreachable since the length of the tape can exceed the new (smaller) diagonal size of the window. Hence the need to ensure the measuring tape body and tip be dragbounds.

**Comment by veillette** [comment]
Closing
