### ISSUE TITLE
More i18n tweaks

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#86]
Using `?stingTest=double` the sim looks like this:

<img width="1916" alt="screen shot 2016-08-03 at 12 56 11 pm" src="https://cloud.githubusercontent.com/assets/5863899/17378075/c67714e8-5979-11e6-91d1-4519c1a56134.png">
- [x] The panels have no apparent max width (using `?stringTest=long` makes that very obvious). Having the panels remain the same width with longer strings would be nice (since the panels are starting to crowd the play area, big problem on iPad).
- [x] EDIT: In other sims, it was decided that the "V" for voltage should be restricted to one character in length (if it isn't already). This should help the equipotential meter's readout, e-field line values, and sensor values from being too long when someone decides to translate them.

@andrewadare @arouinfar can these changes be made?
@arouinfar can you review the sim and see if there is anything else you would like changed?

For phetsims/tasks#661.
Troubleshooting information:
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.15/charges-and-fields_en.html
Version: 1.0.0-dev.15 2016-07-28 14:16:27 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"56e95e01","branch":"master"},"babel":{"sha":"b0a15003","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"charges-and-fields":{"sha":"9163b74d","branch":"master"},"chipper":{"sha":"bdc6b525","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"50af4ae6","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"eaa4be69","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"85b7fc95","branch":"master"},"tandem":{"sha":"6cc3e843","branch":"master"}}

**Comment by phet-steele** [comment]
> In other sims, it was decided that the "V" for voltage should not be i18n-able.

Actually I'm wrong, it was just limited to always being one character, so scratch that suggestion. Edited above.

**Comment by arouinfar** [comment]
Thanks @phet-steele! We should probably allow the panels to expands somewhat before shrinking the strings. In the past, 50px has worked pretty well, but we could go with something smaller like 25 or 30 px. I can mock this up and see how it looks.

I also agree that we don't need to worry about long strings for V if it gets limited to one character. 

By the way, that's a really cool looking equipotential @phet-steele

**Comment by phet-steele** [comment]
> By the way, that's a really cool looking equipotential

Thanks! I don't know if you can tell, but's it's just one e-field line. I think it looks like a koala bear 😄

**Comment by arouinfar** [comment]
If we allow the panel to expand by 50px, it cuts a bit too much into the play area. However, it looks like we've got quite a lot of negative space to the right of the panels and the reset all.
![image](https://cloud.githubusercontent.com/assets/8419308/17497493/5bd9a90c-5d7f-11e6-83b4-f0f93c908815.png)

It may be a little unorthodox, but perhaps we should allow panel to expand by up to 50px. However, the first 25 px of the expansion should be on the <i>right</i> of the panel. The toolbox and reset all will have to shift to the right to maintain their alignment with the panel. The remaining 25px of expansion can occur on the left side of the panel.

Expand by 25px to the right, re-align
![image](https://cloud.githubusercontent.com/assets/8419308/17497376/d664040c-5d7e-11e6-897d-5a0a0465a8c4.png)

An additional 25px expansion on the left
![image](https://cloud.githubusercontent.com/assets/8419308/17497439/1ae147d4-5d7f-11e6-9115-7c01364b3e57.png)

**Comment by andrewadare** [comment]
Regarding the second checkbox for this issue: the suggestion was to make the "V" string in the potential meter only translatable to a single character, to protect from text overruns in the sensor display. Something along these lines was done for Resistance in a Wire: see [this block](https://github.com/phetsims/resistance-in-a-wire/blob/bafd7d2fd8ee20e7a26a83555446eeace841c973/js/resistance-in-a-wire/view/FormulaView.js#L30-L42) in FormulaView.js.

However, I discussed this with @jbphet, and he pointed out that RIAW is quite a different case from the sensor label in C&F, because the display of the equation in RIAW is a critical part of the sim, and text over-runs can get more problematic there because of all the symbols concentrated in one spot. 

He also noted that his code is somewhat experimental, and didn't consider it ready to factor into common code for wide use. For the same reason, it's not a great idea to copy-paste it into the C&F source. It contains hard-coded UTF8 code points serving as boundaries of a range, and it’s not clear yet whether that’s the correct way to solve this problem in general. We’re going to flag the topic of constrained single-character translations for developer meeting next week, but in this case, we agreed that the best thing to do is leave it up to the translator to do something sane and reasonable.

**Comment by andrewadare** [comment]
Regarding the first checkbox, @phet-steele indicated :thumbsup: to the applied changes.

**Comment by andrewadare** [comment]
@phet-steele given the preceding comments, are we good to close this issue now?

**Comment by phet-steele** [comment]
> We’re going to flag the topic of constrained single-character translations for developer meeting next week

@andrewadare are you going to use this issue for the "flag", or can it be closed? (I'm fine with it being closed).

**Comment by andrewadare** [comment]
@phet-steele good point, let's keep it open until then so it remains more prominent. Good to know, though, that this particular issue is resolved for Charges and Fields.

**Comment by pixelzoom** [comment]
According to the 8/25/16 dev meeting agenda, this issue is going to be discussed:

> We’re going to flag the topic of constrained single-character translations for developer meeting next week

Labeling this issue for dev meeting.

**Comment by pixelzoom** [comment]
@jbphet flagged this for 8/25/16 developer meeting discussion.

My 2¢ on pulling a single character off of a translated string, as in resistance-in-a-wire.FormulaView `getFirstNonEmbeddingCharacter`. 

Absolutely not, we should not be doing this - and that applies to CAF and RIAW. 

Many of the [Unicode mathematical operators and symbols](https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode) are multibyte. While we can’t use those symbols now due to lack of font support in some browsers (notably Safari mobile), we shouldn’t do anything that prevents their use in the future. 

Example of how RIAW's approach fails, for multibyte Math symbol ‘𝑹’:

> var symbolR = ‘\u1D479’;
> symbolR.length → 2
> getFirstNonEmbeddingCharacter( symbolR ) → the first byte only, which is garbage

I agree with @andrewadare's comment in https://github.com/phetsims/charges-and-fields/issues/86#issuecomment-241072350: “the best thing to do is leave it up to the translator to do something sane and reasonable”.  And I would add: prevent layout problems by setting `maxWidth` appropriately, rather than making assumptions about text width.

**Comment by pixelzoom** [comment]
To demonstrate the problem that can be caused by indiscriminately pulling the first character off of a translated string...

Here's what RIAW looks like with the Unicode math symbol ‘𝑹’. The symbol is rendered as garbage because we're only using the first byte of a multibyte character.

![screenshot_85](https://cloud.githubusercontent.com/assets/3046552/17908029/dd1c03bc-693b-11e6-8f9d-b372a4a869f3.png)

Here's what it looks like if `getFirstNonEmbeddingCharacter` is disabled. The symbol is rendered correctly.

![screenshot_84](https://cloud.githubusercontent.com/assets/3046552/17908033/e96034b8-693b-11e6-91ad-1c3b6f9f0ef4.png)

**Comment by pixelzoom** [comment]
8/25/16 dev meeting:  Decided to remove `getFirstNonEmbeddingCharacter` from RIAW and not propagate this approach to other sims.

**Comment by phet-steele** [comment]
@andrewadare after this decision, last thing to do here is it might be a good idea to scale the text of the Equipotential meter's readout down with longer strings. I don't feel like many translators will enter a string longer than one character, but a fall back if they do might be nice. The text in the screenshot below should stay in the white area:
<img width="249" alt="screen shot 2016-08-25 at 12 39 56 pm" src="https://cloud.githubusercontent.com/assets/5863899/17981529/4fb0c2b0-6ac1-11e6-8c28-3e387fc40087.png">

**Comment by jbphet** [comment]
I've removed the code from RIAW and did a maintenance release.  Only one translator had added long strings for the characters, and I've asked @oliver-phet to contact him/her and let them know that they will need to fix the translation.

**Comment by oliver-phet** [comment]
Translator has been notified.

**Comment by phet-steele** [comment]
I believe all work is done here, thank you everyone! @andrewadare the commit to the Equipotential meter looks great.
