### ISSUE TITLE
Electric field line represenation in a V2?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/charges-and-fields#99]
Not assigning anyone to this issue currently, but it seems a common request/thought in the past was to add a field line representation to this sim.

This would likely be a fair bit of work, but it might be a good backburner project for a developer like @jessegreenberg at some point.

Mainly making this issue so that we can consider the work involved next time we revisit the sim after initial publication.

**Comment by veillette** [comment]
FYI, at some point charges and fields had an implementation of the electric field lines

http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.5/charges-and-fields_en.html

 It was hidden behind a dialog box. The electric field line would appear when double clicking (or double tapping) an electric field sensor. It turns out to be relatively easy to implement. You may want to redesign  the rather obscure user interaction though.

![image](https://cloud.githubusercontent.com/assets/7633344/18065616/8f1507b0-6e02-11e6-90b0-7e09eb2bd7b5.png)

I can dig up the code but I'll address a reason why you may not want to have electric fields.

**Comment by veillette** [comment]
The commit when we removed the electric field lines

https://github.com/phetsims/charges-and-fields/commit/5e3d597064def6aef7ebf5226b9a0a8a711adfcf

You probably cannot simply undo this commit and expect the sim to be working, but it is a starting point.

**Comment by veillette** [comment]
One of the reason why the electric field lines were removed was due to the fact that the electric field lines do not behave as simply as one would learn in a high school setting. 
Almost every single textbook makes a mentions that  electric field lines must begin on positive charges and terminate on negative charges, or at infinity in the hypothetical case of isolated charges.

Although this is correct, the charges and fields  simulation "seems" to violate this rule.

![image](https://cloud.githubusercontent.com/assets/7633344/18065966/4508d3fc-6e04-11e6-80bc-6d347f1fc594.png)

In the situation above, many of the electric field lines seems to emerge from a central point, a point that is neither at infinity or on a charge, in violation of the previous rule.  In reality the electric field lines are coming from infinity  (from the third dimension) and doing a 90 degrees turn into the plane. 

Note that this issue is already present with the electric potential. There exists a theorem, Earnshaw Theorem, that states that there are no local minima or maxima of the field potential in free space (that is a point that is not on a charge) , only saddle points.  The green equipotential lines indicates there is a maximum of the electric potential at the center of the screen (in free space), However it is a maximum in the x-y plane but is a minimum along the (invisible) z-direction.  Therefore it is a saddle point, so it is not a violation of Earnshaw Theorem   

Both instances are apparent violations of very fundamental rules of electrostatics that can be explained away once you take into account the three dimensional nature of the simulation. 

The difference is that Earnshaw theorem is obscure.  The flash simulation of charges and fields has been around for a while and I doubt that anybody ever brought that up. 

The aforementioned rule about electric field lines is one of the very first thing one learns when drawing electric field lines, so students are more likely to notice this apparent discrepancy.

**Comment by ariel-phet** [comment]
@veillette thanks for the detailed explanation. 

I will bring up with @kathy-phet, and I think for the reasons you mentioned above we will drop this feature request from future discussion!

**Comment by kathy-phet** [comment]
Agreed. Drop feature request.

**Comment by ariel-phet** [comment]
Sounds good. Closing.
